import { db } from "./index";
import { products } from "@shared/schema";
import { eq } from "drizzle-orm";

// 이 스크립트는 기존 상품을 모두 삭제하고 CSV 파일에서 가져온 일본 상품들로 데이터베이스를 다시 채웁니다
async function resetAndSeedAllProducts() {
  try {
    console.log("데이터베이스 상품 초기화 및 재설정 시작...");
    
    // 1. 모든 기존 상품 삭제
    console.log("기존 상품 삭제 중...");
    await db.delete(products);
    
    // 2. CSV 파일에서 가져온 상품 데이터 추가
    console.log("101개의 새로운 상품 데이터 추가 중...");
    
    // CSV에서 가져온 상품 데이터
    const newProducts = [
      // IT 제품
      {
        name: "애플 아이패드 9세대 (Wi-Fi 64GB)",
        description: "일본 내에서 구매 가능한 애플 아이패드 9세대 Wi-Fi 모델. 전국적으로 판매되며 빅카메라나 애플 스토어에서 구매 가능합니다.",
        price: 50000,
        imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["애플", "아이패드", "일본전자제품"],
        location: "애플스토어, 빅카메라 등 전국 매장",
        featured: true,
      },
      {
        name: "소니 무선이어폰 WF-1000XM5",
        description: "소니의 최신 노이즈 캔슬링 무선 이어폰. 일본에서 약 33,000~38,000엔에 요도바시카메라와 빅카메라에서 구매 가능합니다.",
        price: 35000,
        imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["소니", "이어폰", "일본전자제품"],
        location: "요도바시카메라, 빅카메라 등 전국 매장",
        featured: false,
      },
      {
        name: "닌텐도 스위치 OLED 모델",
        description: "더 커진 7인치 OLED 디스플레이를 탑재한 닌텐도 스위치 최신 모델. 일본 내 약 37,000~39,000엔에 판매됩니다.",
        price: 38000,
        imageUrl: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["닌텐도", "게임", "일본전자제품"],
        location: "요도바시카메라, 닌텐도 스토어, 트위스터샵",
        featured: true,
      },
      {
        name: "애플 매직 마우스 2",
        description: "애플의 인체공학적 디자인의 무선 마우스입니다. 멀티터치 표면으로 직관적인 사용이 가능합니다.",
        price: 11000,
        imageUrl: "https://images.unsplash.com/photo-1585051529508-05303d473a3a?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["애플", "마우스", "일본전자제품"],
        location: "애플스토어, 빅카메라",
        featured: false,
      },
      {
        name: "로지텍 무선 키보드 K380",
        description: "가볍고 휴대성이 좋은 로지텍의 인기 무선 키보드. 다중 기기 연결이 가능합니다.",
        price: 3500,
        imageUrl: "https://images.unsplash.com/photo-1561112078-7d24e04c3407?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["로지텍", "키보드", "일본전자제품"],
        location: "빅카메라, 아마존 재팬",
        featured: false,
      },
      {
        name: "샤프 전자노트 WG-S30",
        description: "메모와 필기를 디지털화할 수 있는 전자노트. 일본 샤프의 인기 제품입니다.",
        price: 11000,
        imageUrl: "https://images.unsplash.com/photo-1516131206008-dd041a9764fd?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["샤프", "전자노트", "일본전자제품"],
        location: "요도바시카메라, 문구전문점",
        featured: false,
      },
      {
        name: "안커 보조배터리 PowerCore 10000",
        description: "안커의 인기 보조배터리. 10000mAh 용량으로 스마트폰을 여러 번 충전할 수 있습니다.",
        price: 3500,
        imageUrl: "https://images.unsplash.com/photo-1583474883278-b17f414f2f05?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["안커", "보조배터리", "일본전자제품"],
        location: "돈키호테, 빅카메라, 온라인샵",
        featured: false,
      },
      {
        name: "프린스톤 USB-C 허브 6in1",
        description: "다양한 포트를 제공하는 USB-C 허브. 노트북 사용자에게 필수적인 아이템입니다.",
        price: 4500,
        imageUrl: "https://images.unsplash.com/photo-1605478371310-a9f1e96b4ff4?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["프린스톤", "USB허브", "일본전자제품"],
        location: "요도바시카메라, 아마존",
        featured: false,
      },
      {
        name: "버팔로 외장 SSD 500GB",
        description: "고속 데이터 전송이 가능한 외장 SSD. 휴대성이 좋고 안정적인 성능을 제공합니다.",
        price: 9000,
        imageUrl: "https://images.unsplash.com/photo-1551818176-60579e574b91?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["버팔로", "SSD", "일본전자제품"],
        location: "전자전문점, 온라인",
        featured: false,
      },
      {
        name: "샤프 전자사전 Brain PW-S2 시리즈",
        description: "다양한 언어 학습과 사전 기능을 제공하는 고급 전자사전입니다.",
        price: 20000,
        imageUrl: "https://images.unsplash.com/photo-1518112166137-85f9979a43aa?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["샤프", "전자사전", "일본전자제품"],
        location: "요도바시카메라, 빅카메라",
        featured: false,
      },
      {
        name: "Wacom Intuos S 타블렛",
        description: "디지털 드로잉과 디자인을 위한 타블렛. 초보자도 쉽게 사용할 수 있습니다.",
        price: 9000,
        imageUrl: "https://images.unsplash.com/photo-1626144494295-25393a4b70fb?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["와콤", "타블렛", "일본전자제품"],
        location: "전자전문점, 온라인",
        featured: false,
      },
      {
        name: "JVC 무선 블루투스 헤드폰 HA-A30T",
        description: "가벼운 착용감과 뛰어난 음질을 제공하는 무선 블루투스 헤드폰입니다.",
        price: 6000,
        imageUrl: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["JVC", "헤드폰", "일본전자제품"],
        location: "빅카메라, 요도바시카메라",
        featured: false,
      },
      {
        name: "ELECOM 마우스 M-DY12DB 시리즈",
        description: "정밀한 센서와 인체공학적 디자인의 마우스. 장시간 사용해도 피로감이 적습니다.",
        price: 2000,
        imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["ELECOM", "마우스", "일본전자제품"],
        location: "로프트, 전자전문점, 아마존",
        featured: false,
      },
      {
        name: "BUFFALO Wi-Fi 6 라우터 WSR-5400AX6S",
        description: "최신 Wi-Fi 6 기술을 탑재한 고성능 무선 라우터. 빠른 인터넷 속도를 제공합니다.",
        price: 12000,
        imageUrl: "https://images.unsplash.com/photo-1584478919946-e9b98f602535?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["BUFFALO", "라우터", "일본전자제품"],
        location: "요도바시카메라, 온라인몰",
        featured: false,
      },
      {
        name: "ELECOM 노트북 스탠드",
        description: "노트북의 열 발산과 인체공학적 자세를 위한 스탠드. 접이식 디자인으로 휴대가 편리합니다.",
        price: 2500,
        imageUrl: "https://images.unsplash.com/photo-1602524815325-fb3cca4c1748?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["ELECOM", "노트북스탠드", "일본전자제품"],
        location: "빅카메라, 요도바시카메라, 로프트",
        featured: false,
      },
      {
        name: "Anker USB-C to HDMI 어댑터",
        description: "USB-C 포트를 HDMI 출력으로 변환해주는 어댑터. 노트북과 모니터 연결에 유용합니다.",
        price: 2500,
        imageUrl: "https://images.unsplash.com/photo-1602524815425-408409974077?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["안커", "어댑터", "일본전자제품"],
        location: "빅카메라, 돈키호테, 아마존",
        featured: false,
      },
      {
        name: "KOKUYO 스마트 노트 CamiApp",
        description: "종이 노트에 작성한 내용을 스마트폰 앱으로 디지털화할 수 있는 스마트 노트입니다.",
        price: 1300,
        imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "IT",
        hashtags: ["KOKUYO", "스마트노트", "일본문구"],
        location: "문구 전문점, 로프트",
        featured: false,
      },
      
      // 화장품/뷰티 제품
      {
        name: "비오레 UV 아쿠아리치 선크림",
        description: "일본에서 가장 인기 있는 자외선 차단제 중 하나. 가볍고 산뜻한 사용감과 효과적인 자외선 차단력이 특징입니다.",
        price: 750,
        imageUrl: "https://images.unsplash.com/photo-1556229174-5e80a284afcb?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["비오레", "선크림", "일본화장품"],
        location: "마츠모토키요시 등 전국 드럭스토어",
        featured: true,
      },
      {
        name: "캔메이크 크림치크",
        description: "일본 저가 화장품 브랜드 캔메이크의 인기 제품. 자연스러운 발색과 번짐 없는 지속력으로 인기 있는 크림 타입 블러셔입니다.",
        price: 700,
        imageUrl: "https://images.unsplash.com/photo-1515688594390-b649af70d282?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["캔메이크", "블러셔", "일본화장품"],
        location: "드럭스토어, 로프트",
        featured: false,
      },
      {
        name: "하다라보 고쿠쥰 로션",
        description: "히알루론산이 풍부하게 함유된 보습 로션. 저렴한 가격에 뛰어난 보습력을 자랑합니다.",
        price: 800,
        imageUrl: "https://images.unsplash.com/photo-1616002103028-c3c2496a541b?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["하다라보", "스킨케어", "일본화장품"],
        location: "드럭스토어",
        featured: false,
      },
      {
        name: "시세이도, 완벽한 휩",
        description: "시세이도의 인기 폼 클렌저. 풍부한 거품으로 부드럽게 세안할 수 있습니다.",
        price: 600,
        imageUrl: "https://images.unsplash.com/photo-1571875257727-256c39da42af?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["시세이도", "클렌저", "일본화장품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "DHC 딥 클렌징 오일",
        description: "DHC의 베스트셀러 클렌징 오일. 메이크업과 피지를 효과적으로 제거합니다.",
        price: 1350,
        imageUrl: "https://images.unsplash.com/photo-1473830394358-91588751b241?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["DHC", "클렌징오일", "일본화장품"],
        location: "드럭스토어, DHC 매장",
        featured: false,
      },
      {
        name: "오페라 립틴트 N",
        description: "일본에서 인기 있는 립 틴트. 선명한 발색과 우수한 지속력으로 많은 사랑을 받고 있습니다.",
        price: 1600,
        imageUrl: "https://images.unsplash.com/photo-1544438706-4e18b1101522?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["오페라", "립틴트", "일본화장품"],
        location: "드럭스토어, 로프트, PLAZA",
        featured: false,
      },
      {
        name: "키스미 히로인 롱앤컬 마스카라",
        description: "일본 베스트셀러 마스카라. 긴 속눈썹과 컬링 효과를 동시에 제공합니다.",
        price: 1100,
        imageUrl: "https://images.unsplash.com/photo-1511929858669-552a6cdd23a1?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["키스미", "마스카라", "일본화장품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "마죠리카 마죠르카 마스카라",
        description: "독특한 브러시로 속눈썹을 완벽하게 분리하고 볼륨감을 주는 마스카라입니다.",
        price: 1350,
        imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["마죠리카마죠르카", "마스카라", "일본화장품"],
        location: "드럭스토어, 로프트",
        featured: false,
      },
      {
        name: "세잔느 내추럴 치크 N",
        description: "자연스러운 발색의 저렴한 블러셔. 색상 다양성과 가성비로 인기가 많습니다.",
        price: 500,
        imageUrl: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["세잔느", "블러셔", "일본화장품"],
        location: "드럭스토어, 로프트, PLAZA",
        featured: false,
      },
      {
        name: "루나솔 아이섀도우 팔레트",
        description: "고급스러운 발색과 부드러운 텍스처의 프리미엄 아이섀도우 팔레트입니다.",
        price: 6000,
        imageUrl: "https://images.unsplash.com/photo-1503236823255-94609f598e71?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["루나솔", "아이섀도우", "일본화장품"],
        location: "백화점, 면세점, @cosme STORE",
        featured: false,
      },
      {
        name: "SK-II 페이셜 트리트먼트 에센스",
        description: "SK-II의 대표 제품인 '미라클 워터'. 피부 탄력과 투명도를 개선하는 프리미엄 에센스입니다.",
        price: 21500,
        imageUrl: "https://images.unsplash.com/photo-1626712344719-ee5f42c5df2e?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["SK-II", "에센스", "일본화장품"],
        location: "백화점, 공항면세점, 온라인",
        featured: true,
      },
      {
        name: "시세이도 아네사 퍼펙트 UV 선스크린",
        description: "시세이도의 인기 자외선 차단제. 땀과 물에 강한 워터프루프 기능을 갖춘 고급 선스크린입니다.",
        price: 2500,
        imageUrl: "https://images.unsplash.com/photo-1567733681389-585dc2dccbb8?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["시세이도", "아네사", "일본화장품"],
        location: "드럭스토어, 돈키호테, 면세점",
        featured: true,
      },
      {
        name: "나이브 페이셜 클렌징 폼",
        description: "저자극 성분으로 만들어진 페이셜 클렌저. 순한 사용감으로 민감한 피부에도 적합합니다.",
        price: 400,
        imageUrl: "https://images.unsplash.com/photo-1570194065650-d99fb4a8e0ea?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "BEAUTY",
        hashtags: ["나이브", "클렌징폼", "일본화장품"],
        location: "드럭스토어, 슈퍼마켓",
        featured: false,
      },
      
      // 캐릭터 굿즈
      {
        name: "포켓몬 키링",
        description: "일본 오리지널 포켓몬 캐릭터 키링. 다양한 포켓몬 캐릭터 디자인으로 제공됩니다.",
        price: 800,
        imageUrl: "https://images.unsplash.com/photo-1613771404784-3a9b1a1300af?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "CHARACTER",
        hashtags: ["포켓몬", "키링", "일본캐릭터"],
        location: "포켓몬 센터, 돈키호테",
        featured: true,
      },
      {
        name: "도라에몽 머그컵",
        description: "인기 애니메이션 캐릭터 도라에몽이 디자인된 머그컵. 귀여운 선물용으로 인기가 많습니다.",
        price: 1200,
        imageUrl: "https://images.unsplash.com/photo-1614945181192-c607ee56bb29?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "CHARACTER",
        hashtags: ["도라에몽", "머그컵", "일본캐릭터"],
        location: "돈키호테, 기념품샵",
        featured: false,
      },
      {
        name: "지브리 캐릭터 인형",
        description: "지브리 스튜디오의 인기 캐릭터 인형. 토토로, 가오나시, 포뇨 등 다양한 캐릭터로 제공됩니다.",
        price: 2000,
        imageUrl: "https://images.unsplash.com/photo-1598799115142-afc4909bcc3b?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "CHARACTER",
        hashtags: ["지브리", "인형", "토토로"],
        location: "지브리샵 (도쿄/오사카)",
        featured: false,
      },
      
      // 주류
      {
        name: "야마자키 12년 위스키",
        description: "일본의 대표적인 싱글 몰트 위스키. 세계적으로 인정받는 프리미엄 위스키로, 부드러운 맛과 복합적인 풍미가 특징입니다.",
        price: 18000,
        imageUrl: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "LIQUOR",
        hashtags: ["야마자키", "일본위스키", "프리미엄위스키"],
        location: "주류 전문점, 면세점",
        featured: true,
      },
      {
        name: "하쿠슈 12년 위스키",
        description: "산토리에서 생산하는 싱글 몰트 위스키. 신선하고 가벼운 맛으로 야마자키와 함께 일본 위스키의 대표주자입니다.",
        price: 15000,
        imageUrl: "https://images.unsplash.com/photo-1514218953589-2d7d87afd6e8?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "LIQUOR",
        hashtags: ["하쿠슈", "일본위스키", "프리미엄위스키"],
        location: "주류 전문점, 면세점",
        featured: false,
      },
      {
        name: "닛카 프롬 더 배럴 위스키",
        description: "닛카의 인기 위스키. 합리적인 가격에 풍부한 맛을 즐길 수 있는 블렌디드 위스키입니다.",
        price: 3800,
        imageUrl: "https://images.unsplash.com/photo-1541795795328-f073b763494e?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "LIQUOR",
        hashtags: ["닛카", "일본위스키", "위스키"],
        location: "주류 전문점, 면세점",
        featured: false,
      },
      {
        name: "다사이 23 사케",
        description: "일본의 프리미엄 준마이 다이긴조 사케. 쌀을 23%까지 정미한 고급 사케로, 깨끗하고 부드러운 맛이 특징입니다.",
        price: 6000,
        imageUrl: "https://images.unsplash.com/photo-1578559117711-29f7add363a9?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "LIQUOR",
        hashtags: ["다사이", "사케", "일본술"],
        location: "사케 전문점, 백화점",
        featured: false,
      },
      {
        name: "쿠로키리시마 소주",
        description: "일본의 인기 소주 브랜드. 고구마를 원료로 만들어 부드러운 맛이 특징입니다.",
        price: 1200,
        imageUrl: "https://images.unsplash.com/photo-1609951651556-5334e2706168?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "LIQUOR",
        hashtags: ["쿠로키리시마", "소주", "일본술"],
        location: "주류 전문점, 슈퍼마켓",
        featured: false,
      },
      {
        name: "이이치코 실루엣 소주",
        description: "보리를 주원료로 만든 일본의 대표적인 소주. 깔끔하고 순한 맛으로 인기 있습니다.",
        price: 1500,
        imageUrl: "https://images.unsplash.com/photo-1550850838-eae2649406a1?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "LIQUOR",
        hashtags: ["이이치코", "소주", "일본술"],
        location: "주류 전문점, 슈퍼마켓",
        featured: false,
      },
      {
        name: "쿠보타 만쥬 사케",
        description: "고급 정미 과정을 거친 프리미엄 준마이 다이긴조 사케. 깊고 복합적인 맛이 특징입니다.",
        price: 5000,
        imageUrl: "https://images.unsplash.com/photo-1572388091230-17f44595f7a3?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "LIQUOR",
        hashtags: ["쿠보타", "사케", "일본술"],
        location: "주류 전문점, 백화점",
        featured: false,
      },
      
      // 전자제품/가전
      {
        name: "파나소닉 나노케어 드라이기 EH-NA0J",
        description: "나노이 기술을 적용해 모발에 수분을 공급하며 건조시켜주는 고급 헤어 드라이어입니다.",
        price: 30000,
        imageUrl: "https://images.unsplash.com/photo-1522338140262-f46f5913618a?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "ELECTRONICS",
        hashtags: ["파나소닉", "드라이기", "일본가전"],
        location: "빅카메라, 요도바시카메라",
        featured: true,
      },
      {
        name: "파나소닉 구강세정기 EW-DJ55",
        description: "컴팩트한 디자인의 효과적인 구강세정기. 여행용으로도 적합합니다.",
        price: 13000,
        imageUrl: "https://images.unsplash.com/photo-1575468931897-7dbbd80d4d83?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "ELECTRONICS",
        hashtags: ["파나소닉", "구강세정기", "일본가전"],
        location: "요도바시카메라, 돈키호테",
        featured: false,
      },
      {
        name: "도시바 휴대용 전기면도기",
        description: "휴대가 간편한 소형 전기면도기. 여행용으로 인기 있는 제품입니다.",
        price: 4000,
        imageUrl: "https://images.unsplash.com/photo-1559765953-80a5374d5477?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "ELECTRONICS",
        hashtags: ["도시바", "면도기", "일본가전"],
        location: "빅카메라, 요도바시카메라",
        featured: false,
      },
      {
        name: "샤프 플라즈마클러스터 공기청정기",
        description: "샤프의 플라즈마클러스터 기술이 적용된 고성능 공기청정기. 미세먼지와 냄새 제거에 효과적입니다.",
        price: 20000,
        imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "ELECTRONICS",
        hashtags: ["샤프", "공기청정기", "일본가전"],
        location: "가전 양판점, 빅카메라",
        featured: false,
      },
      {
        name: "오므론 전자혈압계 HEM-7120",
        description: "정확한 혈압 측정이 가능한 가정용 전자혈압계. 사용이 간편하고 신뢰성이 높습니다.",
        price: 5000,
        imageUrl: "https://images.unsplash.com/photo-1631567775881-389f932254b1?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "ELECTRONICS",
        hashtags: ["오므론", "혈압계", "일본가전"],
        location: "드럭스토어, 빅카메라",
        featured: false,
      },
      {
        name: "타이거 미니 전기밥솥 3컵용",
        description: "컴팩트한 사이즈의 고품질 일본 전기밥솥. 1-3인 가구에 적합한 사이즈입니다.",
        price: 10000,
        imageUrl: "https://images.unsplash.com/photo-1544233726-9f1d2cfe73c5?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "ELECTRONICS",
        hashtags: ["타이거", "밥솥", "일본가전"],
        location: "빅카메라, 요도바시카메라",
        featured: false,
      },
      {
        name: "Zojirushi 전기포트 CD-WU30",
        description: "정확한 온도 조절과 보온 기능이 있는 고급 전기포트. 차와 커피 애호가에게 적합합니다.",
        price: 12000,
        imageUrl: "https://images.unsplash.com/photo-1564466809058-bf4114d55352?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "ELECTRONICS",
        hashtags: ["Zojirushi", "전기포트", "일본가전"],
        location: "요도바시카메라, 백화점",
        featured: false,
      },
      {
        name: "무선 마사지건 DOCTORAIR RM-04",
        description: "근육 이완을 위한 고급 마사지건. 여러 단계의 강도 조절과 다양한 헤드를 제공합니다.",
        price: 13000,
        imageUrl: "https://images.unsplash.com/photo-1600880292089-90a6a0d33458?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "ELECTRONICS",
        hashtags: ["DOCTORAIR", "마사지건", "일본가전"],
        location: "돈키호테, 요도바시카메라",
        featured: false,
      },
      
      // 잡화
      {
        name: "포터(Porter) 탱커 백",
        description: "일본의 인기 가방 브랜드 포터의 대표 모델. 내구성이 뛰어나고 실용적인 디자인으로 인기가 많습니다.",
        price: 25000,
        imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["포터", "가방", "일본패션"],
        location: "포터 매장, 백화점",
        featured: false,
      },
      {
        name: "오니츠카 타이거 스니커즈",
        description: "클래식한 디자인의 일본 스니커즈. 편안한 착용감과 독특한 스타일로 유명합니다.",
        price: 12000,
        imageUrl: "https://images.unsplash.com/photo-1626289663338-9224834cc8c5?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["오니츠카타이거", "스니커즈", "일본패션"],
        location: "오니츠카 타이거 매장, 백화점",
        featured: false,
      },
      {
        name: "휴먼 메이드 캡",
        description: "일본 스트릿 패션 브랜드의 인기 캡. 독특한 디자인과 고품질 소재가 특징입니다.",
        price: 6500,
        imageUrl: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["휴먼메이드", "캡", "일본패션"],
        location: "브랜드 매장, 편집샵",
        featured: false,
      },
      {
        name: "스미스앤레더 가죽 키링",
        description: "수제 가죽으로 만들어진 고급 키링. 내구성과 미적 가치를 모두 갖춘 제품입니다.",
        price: 4000,
        imageUrl: "https://images.unsplash.com/photo-1614094082869-cd4e4b2905c7?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["스미스앤레더", "키링", "일본패션"],
        location: "팝업스토어, 온라인 샵",
        featured: false,
      },
      {
        name: "에이글 레인부츠",
        description: "고품질 방수 소재의 세련된 디자인 레인부츠. 비 오는 날에도 스타일리시하게 신을 수 있습니다.",
        price: 12000,
        imageUrl: "https://images.unsplash.com/photo-1608379783095-de1c30ff6617?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["에이글", "레인부츠", "일본패션"],
        location: "브랜드 매장, 백화점",
        featured: false,
      },
      {
        name: "VARZAR 버킷햇",
        description: "트렌디한 디자인의 버킷햇. 일본 젊은이들 사이에서 인기 있는 스트릿 패션 아이템입니다.",
        price: 6000,
        imageUrl: "https://images.unsplash.com/photo-1593476087123-36d1de271f08?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["VARZAR", "버킷햇", "일본패션"],
        location: "온라인, 편집샵",
        featured: false,
      },
      {
        name: "오니츠카 타이거 멕시코66 스니커즈",
        description: "일본의 클래식 스니커즈 브랜드. 레트로한 디자인과 편안한 착용감으로 세계적인 인기를 얻고 있습니다.",
        price: 12000,
        imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["오니츠카타이거", "스니커즈", "일본패션"],
        location: "오니츠카 타이거 매장, 백화점",
        featured: false,
      },
      {
        name: "PORTER 탱커 크로스백",
        description: "실용적인 디자인의 고품질 크로스백. 일본 가방 브랜드 포터의 인기 제품입니다.",
        price: 25000,
        imageUrl: "https://images.unsplash.com/photo-1548172847-9b6ae9b9c3e9?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["PORTER", "크로스백", "일본패션"],
        location: "요시다 가방 매장, 백화점",
        featured: false,
      },
      {
        name: "로에베 아나그램 가죽 지갑",
        description: "스페인 브랜드지만 일본에서 특히 인기가 높은 로에베의 고급 가죽 지갑입니다.",
        price: 65000,
        imageUrl: "https://images.unsplash.com/photo-1580745345925-7c33b63baa99?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["로에베", "지갑", "프리미엄패션"],
        location: "백화점, 긴자 매장, 면세점",
        featured: false,
      },
      {
        name: "에르메스 트윌리 스카프",
        description: "다양한 방법으로 활용 가능한 에르메스의 얇은 실크 스카프. 가방 장식이나 헤어밴드로도 사용 가능합니다.",
        price: 27000,
        imageUrl: "https://images.unsplash.com/photo-1614251055886-faded448bdbd?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["에르메스", "스카프", "프리미엄패션"],
        location: "백화점, 공항면세점",
        featured: false,
      },
      {
        name: "사만사타바사 미니백",
        description: "귀여운 디자인의 미니백. 일본 여성들에게 인기 있는 브랜드의 제품입니다.",
        price: 12000,
        imageUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["사만사타바사", "미니백", "일본패션"],
        location: "사만사타바사 매장, 백화점",
        featured: false,
      },
      {
        name: "애니스(ANNA SUI) 카드지갑",
        description: "독특한 디자인의 카드지갑. 애니스의 시그니처 로고가 특징인 패션 아이템입니다.",
        price: 6000,
        imageUrl: "https://images.unsplash.com/photo-1563904092230-7ec217b65fe2?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["애니스", "카드지갑", "일본패션"],
        location: "백화점, 로프트",
        featured: false,
      },
      {
        name: "비비안 웨스트우드 반지갑",
        description: "독특한 디자인의 영국 디자이너 브랜드 지갑. 일본에서는 특별 컬렉션도 출시됩니다.",
        price: 17000,
        imageUrl: "https://images.unsplash.com/photo-1602351447937-745cb720612f?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["비비안웨스트우드", "지갑", "프리미엄패션"],
        location: "백화점, 공항, 온라인샵",
        featured: false,
      },
      {
        name: "유니클로 U 라인 셔츠",
        description: "유니클로의 프리미엄 라인인 U 시리즈의 셔츠. 미니멀한 디자인과 고품질 소재가 특징입니다.",
        price: 3500,
        imageUrl: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["유니클로", "셔츠", "일본패션"],
        location: "유니클로 매장",
        featured: false,
      },
      {
        name: "무인양품 린넨 셔츠",
        description: "자연 소재인 린넨으로 만든 쾌적한 착용감의 셔츠. 미니멀한 디자인이 특징입니다.",
        price: 4500,
        imageUrl: "https://images.unsplash.com/photo-1589992896344-f774d0a2f324?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["무인양품", "린넨셔츠", "일본패션"],
        location: "무인양품 매장",
        featured: false,
      },
      {
        name: "꼼데가르송 플레이 티셔츠",
        description: "하트 로고로 유명한 꼼데가르송의 인기 라인 플레이 티셔츠. 심플하면서도 독특한 디자인이 특징입니다.",
        price: 10000,
        imageUrl: "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["꼼데가르송", "티셔츠", "일본패션"],
        location: "브랜드 매장, 편집샵",
        featured: false,
      },
      {
        name: "비비안 웨스트우드 티셔츠",
        description: "독특한 로고와 그래픽이 특징인 영국 디자이너 브랜드의 티셔츠. 일본 한정판으로도 출시됩니다.",
        price: 12000,
        imageUrl: "https://images.unsplash.com/photo-1527719327859-c6ce80353573?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["비비안웨스트우드", "티셔츠", "일본패션"],
        location: "백화점, 공식 브랜드 매장",
        featured: false,
      },
      {
        name: "어스 뮤직 앤 에콜로지 원피스",
        description: "일본의 인기 여성복 브랜드. 환경 친화적인 소재와 디자인으로 인기가 있습니다.",
        price: 5000,
        imageUrl: "https://images.unsplash.com/photo-1496217590455-aa63a8350eea?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["어스뮤직", "원피스", "일본패션"],
        location: "브랜드 매장, 온라인",
        featured: false,
      },
      {
        name: "GU 베이직 셔츠",
        description: "유니클로의 자매 브랜드인 GU의 저렴하면서도 품질 좋은 베이직 셔츠입니다.",
        price: 2000,
        imageUrl: "https://images.unsplash.com/photo-1603251578711-3290ca1a0187?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["GU", "셔츠", "일본패션"],
        location: "GU 매장",
        featured: false,
      },
      {
        name: "GU 스웨트 풀오버 후드",
        description: "합리적인 가격의 캐주얼 후드티. 다양한 색상과 편안한 착용감이 특징입니다.",
        price: 2200,
        imageUrl: "https://images.unsplash.com/photo-1556172732-bdbca9258bbd?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["GU", "후드티", "일본패션"],
        location: "GU 매장, 온라인",
        featured: false,
      },
      {
        name: "유니클로 히트텍 이너웨어",
        description: "유니클로의 대표적인 보온 내의. 얇지만 효과적인 보온력으로 겨울철 필수 아이템입니다.",
        price: 1200,
        imageUrl: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["유니클로", "히트텍", "일본패션"],
        location: "유니클로 매장, 공항점",
        featured: true,
      },
      {
        name: "지오다노 재팬 셔츠",
        description: "홍콩 브랜드이지만 일본 시장에 맞춰 출시된 특별 디자인의 셔츠입니다.",
        price: 3500,
        imageUrl: "https://images.unsplash.com/photo-1564240611427-4cc9a0f03a74?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["지오다노", "셔츠", "일본패션"],
        location: "아울렛, 오다이바 등",
        featured: false,
      },
      {
        name: "꼼데가르송 플레이 반팔티",
        description: "하트 로고로 유명한 일본 디자이너 브랜드의 기본 티셔츠. 심플하지만 독특한 디자인이 특징입니다.",
        price: 10000,
        imageUrl: "https://images.unsplash.com/photo-1512400930990-e0bc0bd809df?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["꼼데가르송", "티셔츠", "일본패션"],
        location: "긴자 매장, 도버스트리트마켓",
        featured: false,
      },
      {
        name: "이세이미야케 바오바오 가방",
        description: "기하학적 패턴이 특징인 이세이 미야케의 인기 가방. 다양한 색상으로 출시됩니다.",
        price: 35000,
        imageUrl: "https://images.unsplash.com/photo-1566040590566-2cce0e3d595e?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FASHION",
        hashtags: ["이세이미야케", "바오바오", "일본패션"],
        location: "백화점, 공식 매장, 면세점",
        featured: false,
      },
      
      // 의약품/건강
      {
        name: "에바A 진통제",
        description: "두통, 생리통에 효과적인 일본의 인기 진통제. 카페인이 함유되어 있어 빠른 효과를 볼 수 있습니다.",
        price: 600,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["에바", "진통제", "일본의약품"],
        location: "드럭스토어",
        featured: false,
      },
      {
        name: "로이히츠보코 파스",
        description: "일본의 대표적인 파스 제품. 근육통과 관절통 완화에 효과적이며, 일본 여행객들 사이에서 인기 있는 기념품입니다.",
        price: 400,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["로이히", "파스", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: true,
      },
      {
        name: "파브론 골드 감기약",
        description: "일본의 인기 종합 감기약. 기침, 콧물, 발열 등 다양한 감기 증상에 효과적입니다.",
        price: 900,
        imageUrl: "https://images.unsplash.com/photo-1584362767105-6baae233102e?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["파브론", "감기약", "일본의약품"],
        location: "드럭스토어",
        featured: false,
      },
      {
        name: "사롱파스",
        description: "근육통과 관절통 완화에 효과적인 의약품 패치. 널리 알려진 일본의 인기 제품입니다.",
        price: 500,
        imageUrl: "https://images.unsplash.com/photo-1587854692362-42570bc92ef9?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["사롱파스", "파스", "일본의약품"],
        location: "드럭스토어, 편의점",
        featured: false,
      },
      {
        name: "신루루-A정s (감기약)",
        description: "재채기, 콧물, 기침 등 감기 증상 완화에 효과적인 종합 감기약입니다.",
        price: 900,
        imageUrl: "https://images.unsplash.com/photo-1587854692669-12aff4aeadcc?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["신루루", "감기약", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "용각산 다이렉트 (기침약)",
        description: "목 통증과 기침 완화에 효과적인 약. 직접 섭취하는 분말 타입으로 물 없이 복용 가능합니다.",
        price: 1100,
        imageUrl: "https://images.unsplash.com/photo-1585435557885-e6593bccd0e3?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["용각산", "기침약", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "아리나민 EX 플러스 (비타민제)",
        description: "피로 회복을 돕는 고함량 비타민 B군 보충제. 일본에서 가장 인기 있는 비타민제 중 하나입니다.",
        price: 5500,
        imageUrl: "https://images.unsplash.com/photo-1616671276044-a5c2de2adb66?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["아리나민", "비타민", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "로토 V 로토 프리미엄 안약",
        description: "눈의 피로, 충혈, 가려움을 완화하는 고급 안약. 다양한 유효성분이 함유되어 있습니다.",
        price: 1800,
        imageUrl: "https://images.unsplash.com/photo-1561328399-f94d2ce78ee0?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["로토", "안약", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "페이타스 5.0 파스 (진통소염제)",
        description: "강력한 소염 진통 효과가 있는 파스. 근육통, 관절통, 타박상에 효과적입니다.",
        price: 1200,
        imageUrl: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["페이타스", "파스", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "강력 와카모토 (소화제)",
        description: "식사 후 소화불량, 더부룩함, 속 쓰림 등에 효과적인 소화제입니다.",
        price: 1800,
        imageUrl: "https://images.unsplash.com/photo-1559149251-e9a068427bc9?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["와카모토", "소화제", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "파브론 키즈 감기 시럽",
        description: "어린이용 감기 시럽. 기침, 콧물 등 감기 증상 완화에 효과적입니다.",
        price: 1000,
        imageUrl: "https://images.unsplash.com/photo-1550572017-edd951b55104?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["파브론", "어린이감기약", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "산테 FX NEO 안약",
        description: "일본의 인기 안약. 눈의 피로와 충혈을 완화시키며 시원한 청량감을 주는 제품입니다.",
        price: 1200,
        imageUrl: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["산테", "안약", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "무히 S2a 액체형",
        description: "가려움증, 벌레 물린 데 효과적인 액체형 연고. 빠른 흡수와 냉각 효과가 특징입니다.",
        price: 1000,
        imageUrl: "https://images.unsplash.com/photo-1562729831-8bdf3435b257?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["무히", "항히스타민제", "일본의약품"],
        location: "드럭스토어, 돈키호테",
        featured: false,
      },
      {
        name: "아오지루 건강 음료",
        description: "녹즙을 기반으로 한 건강 음료. 다양한 영양소와 식이섬유가 풍부합니다.",
        price: 1500,
        imageUrl: "https://images.unsplash.com/photo-1622597467836-f3e6707e1fd6?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "HEALTH",
        hashtags: ["아오지루", "녹즙", "일본건강음료"],
        location: "드럭스토어, 슈퍼마켓",
        featured: false,
      },
      
      // 식품/간식
      {
        name: "프링글스 일본 한정맛",
        description: "다양한 일본 한정 맛으로 출시되는 프링글스. 일본에서만 맛볼 수 있는 특별한 맛입니다.",
        price: 250,
        imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["프링글스", "과자", "일본과자"],
        location: "편의점, 돈키호테",
        featured: false,
      },
      {
        name: "기린 복숭아 홍차",
        description: "일본의 인기 음료 브랜드 기린의 달콤한 복숭아 향 홍차. 시원하게 마시는 인기 음료입니다.",
        price: 180,
        imageUrl: "https://images.unsplash.com/photo-1546427660-eb7857c496b4?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["기린", "복숭아홍차", "일본음료"],
        location: "편의점, 슈퍼마켓",
        featured: false,
      },
      {
        name: "로이스 생초콜릿 (Royce Nama Chocolate)",
        description: "홋카이도 특산품인 고급 생초콜릿. 부드러운 텍스처와 깊은 맛으로 유명합니다.",
        price: 750,
        imageUrl: "https://images.unsplash.com/photo-1549007994-cb8bed85524c?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["로이스", "초콜릿", "홋카이도"],
        location: "로이스 매장, 백화점",
        featured: false,
      },
      {
        name: "도쿄 바나나 (Tokyo Banana)",
        description: "도쿄를 대표하는 과자 중 하나로, 바나나 모양의 케이크 안에 바나나 크림이 들어있는 인기 기념품입니다.",
        price: 1200,
        imageUrl: "https://images.unsplash.com/photo-1534312527009-56c7016453e6?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["도쿄바나나", "일본과자", "도쿄기념품"],
        location: "공항, 기차역 키오스크",
        featured: true,
      },
      {
        name: "시로이 코이비토",
        description: "홋카이도의 유명한 과자로, '하얀 연인'이라는 의미의 화이트 초콜릿 쿠키 샌드위치입니다.",
        price: 1200,
        imageUrl: "https://images.unsplash.com/photo-1623152108152-af30fd4772a6?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["시로이코이비토", "쿠키", "홋카이도"],
        location: "공항, 백화점",
        featured: false,
      },
      {
        name: "표고버섯 스낵",
        description: "건강한 표고버섯을 바삭하게 튀겨낸 스낵. 감칠맛과 건강함을 동시에 즐길 수 있습니다.",
        price: 400,
        imageUrl: "https://images.unsplash.com/photo-1603431777007-f748ce30755c?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["표고버섯", "스낵", "일본과자"],
        location: "돈키호테, 슈퍼",
        featured: false,
      },
      {
        name: "야채타임 스낵",
        description: "다양한 야채 맛을 즐길 수 있는 가벼운 스낵. 건강에 신경쓰는 사람들에게 인기 있습니다.",
        price: 150,
        imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["야채타임", "스낵", "일본과자"],
        location: "편의점, 슈퍼마켓",
        featured: false,
      },
      {
        name: "칼비 자가리코 감자스틱",
        description: "감자 맛 스틱 과자. 바삭한 식감과 다양한 맛으로 일본에서 인기 있는 간식입니다.",
        price: 180,
        imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["자가리코", "감자스틱", "일본과자"],
        location: "편의점, 슈퍼마켓, 돈키호테",
        featured: false,
      },
      {
        name: "메이지 마이쵸코렛",
        description: "메이지의 인기 초콜릿 제품. 작은 크기로 다양한 맛을 즐길 수 있는 제품입니다.",
        price: 250,
        imageUrl: "https://images.unsplash.com/photo-1514517604298-cf80e0fb7f1e?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["메이지", "초콜릿", "일본과자"],
        location: "편의점, 슈퍼마켓",
        featured: false,
      },
      {
        name: "프리츠 스틱과자",
        description: "가늘고 긴 스틱 형태의 짭조름한 스낵. 다양한 맛으로 출시되는 인기 과자입니다.",
        price: 130,
        imageUrl: "https://images.unsplash.com/photo-1530904613557-b405de3fb731?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["프리츠", "스틱과자", "일본과자"],
        location: "편의점, 슈퍼마켓",
        featured: false,
      },
      {
        name: "하이츄 젤리캔디",
        description: "부드러운 식감의 과일 맛 젤리 캔디. 다양한 맛으로 출시되는 일본의 인기 사탕입니다.",
        price: 150,
        imageUrl: "https://images.unsplash.com/photo-1471943038886-87c772c31467?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["하이츄", "젤리캔디", "일본과자"],
        location: "편의점, 슈퍼마켓",
        featured: false,
      },
      {
        name: "도라야키 팥 팬케이크",
        description: "도라에몽이 좋아하는 과자로 유명한 전통 디저트. 팥앙금이 들어간 팬케이크 샌드위치입니다.",
        price: 200,
        imageUrl: "https://images.unsplash.com/photo-1623194490972-eb215a4fa512?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["도라야키", "팬케이크", "일본과자"],
        location: "편의점, 슈퍼마켓, 기념품샵",
        featured: false,
      },
      {
        name: "킷캣 일본 한정맛 (녹차, 사케 등)",
        description: "일본에서만 구할 수 있는 특별한 맛의 킷캣 초콜릿. 녹차, 딸기, 사케 등 다양한 일본 현지 맛으로 출시됩니다.",
        price: 400,
        imageUrl: "https://images.unsplash.com/photo-1581226085223-81ef08740880?auto=format&fit=crop&w=800&h=400&q=80",
        countryId: "japan",
        category: "FOOD",
        hashtags: ["킷캣", "초콜릿", "일본과자"],
        location: "편의점, 슈퍼마켓, 기념품점",
        featured: false,
      }
    ];
    
    // 데이터베이스에 상품 추가
    const productsWithTimestamps = newProducts.map(product => ({
      ...product,
      createdAt: new Date(),
      updatedAt: new Date(),
    }));
    
    await db.insert(products).values(productsWithTimestamps);
    
    console.log(`${productsWithTimestamps.length}개의 상품이 성공적으로 추가되었습니다.`);
  } catch (error) {
    console.error("상품 데이터 초기화 및 추가 중 오류 발생:", error);
  }
}

// 스크립트 실행
resetAndSeedAllProducts();